spring.application.name=tocho5


#Version
API_KS-version=KS-Version 1.0.0

r2.endpoint=https://7187a6b46cc1b545de37d29582df1592.r2.cloudflarestorage.com
r2.bucketName=tocho5-dev
r2.accessKeyId=1ead31115d17e0687a4d89b3d9861093
r2.secretAccessKey=6d2508902f012b1e93a14d237674564d98b4447c04bad9719ff6eed638a8c1d3
r2.publicBaseUrl=https://media.tochero5.mx

#dev_lab
#spring.datasource.url=jdbc:mysql://localhost:3306/tocho5?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=aisha200

# --- Datasource: toma todo de ENV ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=60000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB



#   KEYCLOAK / JWT (BACK)


spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.tochero5.mx/realms/tochero5
